---
# nginx
- name: Create CentOS ISO directory.
  file: path={{ pxe_server_iso_mount_path }} state=directory

- name: Create kickstart files directory.
  file: path=/var/www/html/kickstart state=directory

- name: Copy pxe-server nginx config in place .
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/pxe-server.conf
  notify: reload nginx

# tftp
- name: Create pxelinux directories.
  file: path=/var/lib/tftpboot/{{ item }} state=directory
  with_items:
    - pxelinux.cfg
    - pxelinux

- name: Copy syslinux files.
  copy: src=/usr/share/syslinux/{{ item }} dest=/var/lib/tftpboot/
  with_items:
    - pxelinux.0
    - menu.c32

# download ISO
- name: Download isolinux files from http://ftp.iij.ad.jp/pub/linux/centos/7/os/x86_64/isolinux
  get_url: url=http://ftp.iij.ad.jp/pub/linux/centos/7/os/x86_64/isolinux/{{ item }} dest=/var/lib/tftpboot/{{ item }}
  with_items:
    - initrd.img
    - vmlinuz

- name: Download centos7.iso
  get_url: url={{ pxe_server_iso_download_path }} dest={{ pxe_server_iso_file_path }}

# ISO mount
- name: Mount the CentOS image.
  mount: name={{ pxe_server_iso_mount_path }} src={{ pxe_server_iso_file_path }} opts=ro,loop fstype=iso9660 state=mounted

# PXE menu.
- name: Copy default menu.
  template: src=default.menu.j2 dest=/var/lib/tftpboot/pxelinux.cfg/default
